# Generated by Django 5.1 on 2024-08-10 00:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m7_python', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inmuebles',
            name='id_comuna',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='m7_python.comuna'),
        ),
        migrations.AddField(
            model_name='inmuebles',
            name='id_region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='m7_python.region'),
        ),
        migrations.AddField(
            model_name='inmuebles',
            name='id_tipo_inmueble',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='m7_python.tipo_inmueble'),
        ),
        migrations.AddField(
            model_name='inmuebles',
            name='id_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inmuebles',
            name='m2_terreno',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='inmuebles',
            name='numero_est',
            field=models.IntegerField(default=0),
        ),
    ]
